[project]
name = "skyvern-langchain"
version = "0.2.1"
description = ""
authors = [{ name = "lawyzheng", email = "lawy@skyvern.com" }]
requires-python = ">=3.11,<3.14"
readme = "README.md"

dependencies = [
    "skyvern>=0.2.0",
    "langchain>=0.3.19,<0.4",
    "langchain-core>=0.3.81",
    "urllib3>=2.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["twine>=6.1.0,<7"]

[tool.hatch.build.targets.sdist]
include = ["skyvern_langchain"]

[tool.hatch.build.targets.wheel]
include = ["skyvern_langchain"]
